set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(_XBAX_HOST_CLENG "")
if(DEFINED XBAX_HOST_CLENG AND NOT "${XBAX_HOST_CLENG}" STREQUAL "")
  set(_XBAX_HOST_CLENG "${XBAX_HOST_CLENG}")
elseif(DEFINED ENV{XBAX_HOST_CLENG} AND NOT "$ENV{XBAX_HOST_CLENG}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{XBAX_HOST_CLENG}" _XBAX_HOST_CLENG)
endif()

set(_XBAX_HOST_CLENGXX "")
if(DEFINED XBAX_HOST_CLENGXX AND NOT "${XBAX_HOST_CLENGXX}" STREQUAL "")
  set(_XBAX_HOST_CLENGXX "${XBAX_HOST_CLENGXX}")
elseif(DEFINED ENV{XBAX_HOST_CLENGXX} AND NOT "$ENV{XBAX_HOST_CLENGXX}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{XBAX_HOST_CLENGXX}" _XBAX_HOST_CLENGXX)
elseif(_XBAX_HOST_CLENG)
  set(_XBAX_HOST_CLENGXX "${_XBAX_HOST_CLENG}")
endif()

set(_XBAX_HOST_LED "")
if(DEFINED XBAX_HOST_LED AND NOT "${XBAX_HOST_LED}" STREQUAL "")
  set(_XBAX_HOST_LED "${XBAX_HOST_LED}")
elseif(DEFINED ENV{XBAX_HOST_LED} AND NOT "$ENV{XBAX_HOST_LED}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{XBAX_HOST_LED}" _XBAX_HOST_LED)
endif()

if(_XBAX_HOST_CLENG)
  set(CMAKE_C_COMPILER "${_XBAX_HOST_CLENG}" CACHE FILEPATH "" FORCE)
else()
  set(CMAKE_C_COMPILER clang CACHE FILEPATH "" FORCE)
endif()

if(_XBAX_HOST_CLENGXX)
  set(CMAKE_CXX_COMPILER "${_XBAX_HOST_CLENGXX}" CACHE FILEPATH "" FORCE)
else()
  set(CMAKE_CXX_COMPILER clang++ CACHE FILEPATH "" FORCE)
endif()

if(_XBAX_HOST_LED)
  set(CMAKE_LINKER "${_XBAX_HOST_LED}" CACHE FILEPATH "" FORCE)
endif()

if("${CMAKE_CXX_COMPILER}" STREQUAL "${CMAKE_C_COMPILER}")
  set(CMAKE_CXX_COMPILER_ARG1 "--driver-mode=g++" CACHE STRING "" FORCE)
else()
  set(CMAKE_CXX_COMPILER_ARG1 "" CACHE STRING "" FORCE)
endif()

set(CMAKE_C_COMPILER_TARGET x86_64-w64-mingw32 CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-mingw32 CACHE STRING "")
set(_XBAX_MINGW_TRIPLE x86_64-w64-mingw32)

set(CMAKE_C_COMPILER_FORCED TRUE CACHE BOOL "" FORCE)
set(CMAKE_CXX_COMPILER_FORCED TRUE CACHE BOOL "" FORCE)
set(CMAKE_C_COMPILER_WORKS TRUE CACHE BOOL "" FORCE)
set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE BOOL "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_XBAX_MINGW_SYSROOT "")
if(DEFINED ENV{XBAX_WINDOWS_SYSROOT} AND NOT "$ENV{XBAX_WINDOWS_SYSROOT}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{XBAX_WINDOWS_SYSROOT}" _XBAX_MINGW_SYSROOT)
else()
  find_program(_XBAX_MINGW_GCC NAMES ${_XBAX_MINGW_TRIPLE}-gcc)
  if(_XBAX_MINGW_GCC)
    execute_process(
      COMMAND "${_XBAX_MINGW_GCC}" -print-sysroot
      OUTPUT_VARIABLE _XBAX_MINGW_SYSROOT_RAW
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
    )
    if(_XBAX_MINGW_SYSROOT_RAW)
      file(TO_CMAKE_PATH "${_XBAX_MINGW_SYSROOT_RAW}" _XBAX_MINGW_SYSROOT)
    endif()
  endif()
endif()

if(_XBAX_MINGW_SYSROOT)
  set(CMAKE_SYSROOT "${_XBAX_MINGW_SYSROOT}" CACHE PATH "" FORCE)
  list(PREPEND CMAKE_FIND_ROOT_PATH
    "${_XBAX_MINGW_SYSROOT}"
    "${_XBAX_MINGW_SYSROOT}/${_XBAX_MINGW_TRIPLE}"
  )
endif()

set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)
