# gen_bridge_link.cmake — emit a Go source file with #cgo LDFLAGS lines that
# reference every libclang*.a and libLLVM*.a archive in the cleng prefix.
#
# Invoked at build time from the top-level CMakeLists.txt:
#
#   cmake -DCLENG_PREFIX=<dir> -DOUT_FILE=<.go file> -P gen_bridge_link.cmake
#
# Output is wrapped in --start-group / --end-group so cycles between e.g.
# clangFrontend ⇄ clangSerialization ⇄ clangParse resolve in a single pass.
# Hand-curated flags (CXXFLAGS, system libs) live in bridge_link.go and are
# not emitted here.

if(NOT DEFINED CLENG_PREFIX)
  message(FATAL_ERROR "gen_bridge_link.cmake: CLENG_PREFIX must be set")
endif()
if(NOT DEFINED OUT_FILE)
  message(FATAL_ERROR "gen_bridge_link.cmake: OUT_FILE must be set")
endif()

set(_lib_dir "${CLENG_PREFIX}/lib")

if(NOT IS_DIRECTORY "${_lib_dir}")
  message(FATAL_ERROR "gen_bridge_link.cmake: ${_lib_dir} does not exist")
endif()

# Discover every static archive. We deliberately glob both clang* and LLVM*.
file(GLOB _clang_libs RELATIVE "${_lib_dir}" "${_lib_dir}/libclang*.a")
file(GLOB _llvm_libs  RELATIVE "${_lib_dir}" "${_lib_dir}/libLLVM*.a")

# Drop the libclang.a / libclang.dll.a libclang shared library import libs —
# we want the static driver/frontend stack, not the C bindings DLL.
list(FILTER _clang_libs EXCLUDE REGEX "^libclang\\.(a|dll\\.a)$")

# Sort for determinism.
list(SORT _clang_libs)
list(SORT _llvm_libs)

# Translate "libFoo.a" -> "-lFoo".
set(_l_flags "")
foreach(_a IN LISTS _clang_libs _llvm_libs)
  string(REGEX REPLACE "^lib(.*)\\.a$" "-l\\1" _flag "${_a}")
  list(APPEND _l_flags "${_flag}")
endforeach()

# Emit one #cgo line per library so cgo's parser handles the long list cleanly
# (it has historically choked on very long single-line directives).
set(_body "//go:build windows && amd64\n\n")
string(APPEND _body "// Code generated by cleng/scripts/gen_bridge_link.cmake. DO NOT EDIT.\n")
string(APPEND _body "//\n")
string(APPEND _body "// Regenerated whenever the clang-engine target is rebuilt. Lists every\n")
string(APPEND _body "// libclang*.a and libLLVM*.a archive installed under the cleng prefix.\n")
string(APPEND _body "//\n")
string(APPEND _body "// Hand-curated CXXFLAGS, system libs, and stdc++/pthread linkage live in\n")
string(APPEND _body "// bridge_link.go.\n\n")
string(APPEND _body "package cgobridge\n\n")
string(APPEND _body "/*\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -L${CLENG_PREFIX}/lib\n")
string(APPEND _body "#cgo windows,amd64 CXXFLAGS: -I${CLENG_PREFIX}/include\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -Wl,--start-group\n")
foreach(_f IN LISTS _l_flags)
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: ${_f}\n")
endforeach()
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -Wl,--end-group\n")
# System libs go AFTER the group so unresolved __imp_* / GUID references
# pulled in from libLLVMSupport (Windows version, COM, registry, etc.) can
# be satisfied. mingw-ld is single-pass for ungrouped libs, so order matters.
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lversion -luuid -lole32 -loleaut32\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lws2_32 -lntdll -ladvapi32 -lpsapi\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lshell32 -limagehlp -lshlwapi\n")
string(APPEND _body "*/\n")
string(APPEND _body "import \"C\"\n")

file(WRITE "${OUT_FILE}" "${_body}")
message(STATUS "gen_bridge_link.cmake: wrote ${OUT_FILE} (${_l_flags})")
