# gen_bridge_link.cmake — emit a Go source file with #cgo LDFLAGS lines that
# reference every static clang/LLVM library in the cleng prefix.
#
# Invoked at build time from the top-level CMakeLists.txt:
#
#   cmake -DCLENG_PREFIX=<dir> -DOUT_FILE=<.go file> -P gen_bridge_link.cmake
#
# GNU-style archive builds use --start-group / --end-group so cycles between
# e.g. clangFrontend ⇄ clangSerialization ⇄ clangParse resolve in a single
# pass. Native Windows clang builds emit .lib files and are linked directly.

if(NOT DEFINED CLENG_PREFIX)
  message(FATAL_ERROR "gen_bridge_link.cmake: CLENG_PREFIX must be set")
endif()
if(NOT DEFINED OUT_FILE)
  message(FATAL_ERROR "gen_bridge_link.cmake: OUT_FILE must be set")
endif()

set(_lib_dir "${CLENG_PREFIX}/lib")

if(NOT IS_DIRECTORY "${_lib_dir}")
  message(FATAL_ERROR "gen_bridge_link.cmake: ${_lib_dir} does not exist")
endif()

# Discover every static library. We deliberately glob both clang* and LLVM*.
file(GLOB _clang_libs_gnu  RELATIVE "${_lib_dir}" "${_lib_dir}/libclang*.a")
file(GLOB _llvm_libs_gnu   RELATIVE "${_lib_dir}" "${_lib_dir}/libLLVM*.a")
file(GLOB _clang_libs_msvc RELATIVE "${_lib_dir}" "${_lib_dir}/clang*.lib" "${_lib_dir}/libclang*.lib")
file(GLOB _llvm_libs_msvc  RELATIVE "${_lib_dir}" "${_lib_dir}/LLVM*.lib"  "${_lib_dir}/libLLVM*.lib")

# Drop the libclang C bindings import/static library — we want the driver /
# frontend stack, not the C API layer.
list(FILTER _clang_libs_gnu EXCLUDE REGEX "^libclang\.(a|dll\.a)$")
list(FILTER _clang_libs_msvc EXCLUDE REGEX "^(lib)?clang\.lib$")

# Sort for determinism.
list(SORT _clang_libs_gnu)
list(SORT _llvm_libs_gnu)
list(SORT _clang_libs_msvc)
list(SORT _llvm_libs_msvc)

set(_link_mode "")
set(_l_flags "")
if(_clang_libs_msvc OR _llvm_libs_msvc)
  set(_link_mode "msvc")
  foreach(_lib IN LISTS _clang_libs_msvc _llvm_libs_msvc)
    string(REGEX REPLACE "^(lib)?(.*)\.lib$" "-l\\2" _flag "${_lib}")
    list(APPEND _l_flags "${_flag}")
  endforeach()
elseif(_clang_libs_gnu OR _llvm_libs_gnu)
  set(_link_mode "gnu")
  foreach(_a IN LISTS _clang_libs_gnu _llvm_libs_gnu)
    string(REGEX REPLACE "^lib(.*)\.a$" "-l\\1" _flag "${_a}")
    list(APPEND _l_flags "${_flag}")
  endforeach()
else()
  message(FATAL_ERROR "gen_bridge_link.cmake: no clang/LLVM static libraries found under ${_lib_dir}")
endif()

# Emit one #cgo line per library so cgo's parser handles the long list cleanly
# (it has historically choked on very long single-line directives).
set(_body "//go:build windows && amd64\n\n")
string(APPEND _body "// Code generated by cleng/scripts/gen_bridge_link.cmake. DO NOT EDIT.\n")
string(APPEND _body "//\n")
string(APPEND _body "// Regenerated whenever the clang-engine target is rebuilt. Lists every\n")
string(APPEND _body "// static clang/LLVM library installed under the cleng prefix.\n")
string(APPEND _body "//\n")
string(APPEND _body "// Link mode: ${_link_mode}.\n\n")
string(APPEND _body "package cgobridge\n\n")
string(APPEND _body "/*\n")
string(APPEND _body "#cgo windows,amd64 CXXFLAGS: -I${CLENG_PREFIX}/include\n")
if(_link_mode STREQUAL "gnu")
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: -L${CLENG_PREFIX}/lib\n")
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: -Wl,--start-group\n")
  foreach(_f IN LISTS _l_flags)
    string(APPEND _body "#cgo windows,amd64 LDFLAGS: ${_f}\n")
  endforeach()
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: -Wl,--end-group\n")
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: -static -lstdc++ -lpthread\n")
else()
  string(APPEND _body "#cgo windows,amd64 LDFLAGS: -L${CLENG_PREFIX}/lib\n")
  foreach(_f IN LISTS _l_flags)
    string(APPEND _body "#cgo windows,amd64 LDFLAGS: ${_f}\n")
  endforeach()
endif()
# System libs go after the LLVM/Clang libraries so unresolved Win32 / COM /
# registry references from the archive set can be satisfied.
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lversion -luuid -lole32 -loleaut32\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lws2_32 -lntdll -ladvapi32 -lpsapi\n")
string(APPEND _body "#cgo windows,amd64 LDFLAGS: -lshell32 -limagehlp -lshlwapi\n")
string(APPEND _body "*/\n")
string(APPEND _body "import \"C\"\n")

file(WRITE "${OUT_FILE}" "${_body}")
message(STATUS "gen_bridge_link.cmake: wrote ${OUT_FILE} (${_link_mode}: ${_l_flags})")
