// bridge.cpp — C++ shim that exposes Clang's driver entry point to Go.
//
// Clang ships the driver under the C++ symbol `clang_main` (declared in
// `clang/tools/driver/driver.cpp` of llvm-project). We re-export it with C
// linkage so cgo can call it directly. The real Clang/LLVM libraries are
// linked statically via the LDFLAGS in bridge_link.go (which is generated by
// the CMake build to point at build/engine/clang-windows-amd64/lib).
//
// We deliberately avoid pulling in clang/tools/driver/driver.cpp itself, so
// that there is exactly one `main` in the final binary — Go's runtime entry
// point — and Clang is invoked purely as a library.

#include <cstddef>

namespace llvm {
class ToolContext;
}

// Forward declaration matching clang/tools/driver/driver.cpp:
//   int clang_main(int Argc, char **Argv, const llvm::ToolContext &);
// We pass a default-constructed ToolContext; Clang only uses it to recover
// argv[0] / the install dir, both of which it will re-derive from argv.
extern "C" int clang_main(int Argc, char **Argv,
                          const llvm::ToolContext &ToolContext);

namespace llvm {
// ToolContext is a small POD-ish struct in LLVM (Path, PrependArg, NeedsPrependArg).
// We define a permissive stand-in so the shim compiles without dragging the
// LLVM headers into the cgo build. The real layout will come from the linked
// LLVM libraries; only zero-initialised fields are read by clang_main when
// invoked this way.
class ToolContext {
public:
  const char *Path = nullptr;
  const char *PrependArg = nullptr;
  bool NeedsPrependArg = false;
};
} // namespace llvm

extern "C" int cleng_clang_main(int argc, char **argv) {
  llvm::ToolContext ctx{};
  if (argc > 0 && argv != nullptr) {
    ctx.Path = argv[0];
  }
  return clang_main(argc, argv, ctx);
}
